# Especifica a versão da sintaxe do Docker Compose
version: '3.8'

# Define os serviços (contêineres) que compõem sua aplicação
services:
  # O nome do nosso serviço principal
  app:
    # Constrói a imagem usando o Dockerfile no diretório atual (.)
    build: .
    # Um nome amigável para o contêiner que será criado
    container_name: estoque_app
    # Mapeia a porta 3000 do seu computador (host) para a porta 3000 do contêiner
    ports:
      - "3000:3000"
    # Define os volumes para persistir os dados
    # Isso é MUITO IMPORTANTE: garante que seus arquivos JSON não sejam apagados
    # ao recriar o contêiner.
    volumes:
      # Mapeia a pasta 'data' local para a pasta onde o app espera os JSONs
      - ./data/items.json:/app/backend/items.json
      - ./data/sales.json:/app/backend/sales.json
    # Política de reinicialização: sempre reiniciar o contêiner se ele parar,
    # a menos que você o pare manualmente.
    restart: unless-stopped
